name = "dendashboard"
main = "src/worker.js"
compatibility_date = "2024-01-01"

[vars]
DATABASE_NAME = "dendashboard"
CONTAINER_NAME = "dendbcontainer"

# These will be set in Cloudflare's dashboard
# COSMOS_ENDPOINT
# COSMOS_KEY
# ADMIN_PASSWORD
# JWT_SECRET 